### ISSUE TITLE
It is broken in Fedora 36

### ISSUE THREAD

**Issue by Jedsek** [vala-lang/vala-language-server#239]
I typed `vala-language-server --version`:

```
vala-language-server: symbol lookup error: vala-language-server: undefined symbol: vala_method_call_get_call
```

It works fine if I compile it manually.

**Comment by Prince781** [comment]
Ack. Is this from the official repo or the OBS repo?

**Comment by Jedsek** [comment]
The former: 
`sudo dnf info vala-language-server`: 
```
Last metadata expiration check: 0:00:36 ago on Fri 29 Apr 2022 06:57:21 PM CST.
Installed Packages
Name         : vala-language-server
Version      : 0.48.4
Release      : 3.fc36
Architecture : x86_64
Size         : 822 k
Source       : vala-language-server-0.48.4-3.fc36.src.rpm
Repository   : @System
From repo    : fedora
Summary      : Language server for the Vala programming language
URL          : https://github.com/Prince781/vala-language-server
License      : LGPLv2+
Description  : Provides code intelligence for Vala (and also Genie).
             : Used with an editor and a plugin that supports the Language Server Protocol.
```

**Comment by Prince781** [comment]
I think Fedora 36 is not out yet, right? Wouldn't you use rawhide? Does that have the same issue?

In any case, we need to file a bug report to the maintainers of this package. I know some recent version of Vala changed the API for `MethodCall` and made it extend `CallableExpression`. I think this happened before the 0.56 release, so perhaps it's just that the version of Vala in the repos is out of date.

**Comment by amz-x** [comment]
Hi @Jedsek & @Prince781 I've submitted an update for Fedora 36 & Fedora 37 (Rawhide)

F36 Update: https://bodhi.fedoraproject.org/updates/FEDORA-2022-636096c82a
F36 Build: https://koji.fedoraproject.org/koji/buildinfo?buildID=1963521

@Jedsek please let me know if the following update works for you:
https://kojipkgs.fedoraproject.org//packages/vala-language-server/0.48.4/4.fc36/x86_64/vala-language-server-0.48.4-4.fc36.x86_64.rpm

**Comment by Jedsek** [comment]
It works now, thanks.
