### ISSUE TITLE
About support for null-safe access operator

### ISSUE THREAD

**Issue by akarin123** [vala-lang/vala-language-server#256]
**Describe the bug**
It seems that currently vala-language-server cannot analyze null-safe access operator [(null-safe member access)](https://gitlab.gnome.org/GNOME/vala/-/merge_requests/90) and report errors. However the example code can be successfully compiled and run since vala has supported null-safe access operator since 0.53.1

**Software**
OS and version: Linux Mint 20.1
Code editor: VS Code 1.55.2
Vala Language Server: vala-language-server 0.48.5
Vala version (`valac --version`): vala 0.54.8

**To Reproduce**
Example code:
```vala
public class AAA {
  public string s { get; set; }

  public void print() {
    message(s);
  }
}

void main() {
  AAA a = new AAA() { s = "hello" };
  a?.print(); // prints "hello"
  a = null;
  a?.print(); // does nothing
  string str = a?.s ?? "null";
  message(@"the string is '$(str)'"); // prints "the string is 'null'"
}
```

<img width="640" alt="error" src="https://user-images.githubusercontent.com/30003315/180941574-66d1b480-d18a-4a46-92d9-0a930d207748.png">

<img width="640" alt="result" src="https://user-images.githubusercontent.com/30003315/180941639-ec538e7a-5f42-482f-8914-7a2a46337101.png">

**Comment by Prince781** [comment]
Just curious, are you sure you're using VLS 0.48.5? Print `vala-language-server --version`

**Comment by akarin123** [comment]
It's the results.
<img width="403" alt="result" src="https://user-images.githubusercontent.com/30003315/183258089-79c3bdec-8fa4-42b8-bff9-f4f09914f02d.png">

**Comment by Prince781** [comment]
libvala is `0.48`, while your `vala` is 0.54.8. This means that VLS is linked to an older version of the Vala compiler. null-safe member accesses were implemented in Vala 0.54 and VLS supports them since fb5cbb9310f763e27af39111ecbb389e90778344

**Comment by Prince781** [comment]
Do `ldd $(which vala)`, `which vala`, and `which vala-language-server`

**Comment by akarin123** [comment]
Thx! It should be that VLS is linked to `libvala-0.48` while valac is linked to `libvala-0.54`.
<img width="469" alt="resss" src="https://user-images.githubusercontent.com/30003315/183260922-7559e032-bb48-4849-8be8-1808e954b601.png">

**Comment by Prince781** [comment]
So can I close this?

**Comment by akarin123** [comment]
Yes, thx!
