### ISSUE TITLE
Add support for autocomplete for object initialization fields 

### ISSUE THREAD

**Issue by colinkiama** [vala-lang/vala-language-server#257]
For example, while writing this code block:

```vala
var label = new Gtk.Label () {
    text = "Hello World"
};
```

 `Gtk.Label` field suggestions should be displayed while writing the line for the `text` field.

**Comment by Prince781** [comment]
This should hopefully be less complicated to achieve now that [`Vala.MemberInitializer` is a `Vala.Expression`](https://gitlab.gnome.org/GNOME/vala/-/commit/86bc23f2d7295ae3b2f5f79449d2c5a4a7a93a58) (wasn't true the last time I checked).

**Comment by colinkiama** [comment]
I'm sorry, this is a clone of #242. I just noticed now
