### ISSUE TITLE
Question: Am I able to ignore  "missing" symbols, types, etc

### ISSUE THREAD

**Issue by shmup** [vala-lang/vala-language-server#258]
I know this is probably not the correct approach, but I'd like to be able to define a few ignores.

Particularly, a file I'm working in right now is littered with diagnostics such as:

```
[vala] The symbol `Gtk' could not be found [E]
[vala] The symbol `Midori' could not be found [E]
[vala] The symbol `Peas' could not be found [E]
[vala] The type name `Cancellable' could not be found [E]
```

This is a project I am successfully building, and such things are not really missing. I know the "right way" to handle this isn't defining ignores, but, I'd like to anyways (for now). Similar to how, in Lua, I do:

```
  "Lua.diagnostics.globals": [
    "DecodeBase64",
    "EncodeBase64"
   ]
```

Also, I'm pretty ignorant, so I wasn't sure if this was all a case of:

> [coc.nvim] CMake build system is not currently supported. Only Meson is. See https://github.com/vala-lang/vala-language-server/issues/73

I'm thinking it's probably not.

Anyways, thanks!

**Comment by Prince781** [comment]
Are you working with a Vala CMake project?

**Comment by shmup** [comment]
@Prince781 yep, this project https://github.com/shmup/midori

**Comment by Prince781** [comment]
Please see #73. The answer to your question is that you can't ignore these issues, and the fix should be to support CMake.
