### ISSUE TITLE
VLS should exit after a while if it receives no request

### ISSUE THREAD

**Issue by JCWasmx86** [vala-lang/vala-language-server#266]
Sadly current (43.0) GNOME-Builder has the problem, that sometimes language servers are not stopped and still run after Builder is closed.

As long as this is happening, there should be e.g. a timeout of 60 minutes. If no request was received it should simply shutdown.

An example:

![Screenshot from 2022-09-22 19-48-38](https://user-images.githubusercontent.com/63594136/191817174-89fc0db0-dc98-48c6-8ce7-d0066afb60f9.png)

There were 12 instances of VLS running each consuming around 1.2GB RAM. This is a lot of used RAM that makes everything else laggy.

It would be just a temporary fix until this is fixed

**Comment by Prince781** [comment]
I'd lean towards "this should be solved upstream", but if the workaround is simple and won't affect other language clients, then I'll support it.

First we have to see if GNOME Builder sends its info in the [`InitializeParams`](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#initializeParams)

**Comment by JCWasmx86** [comment]
Ah well, I entirely forgot this issue. This issue is no longer relevant, as I can't reproduce it anymore on GNOME-Builder
