### ISSUE TITLE
Ubuntu package 22.10 still needs to be added.

### ISSUE THREAD

**Issue by EsoCoding** [vala-lang/vala-language-server#275]
Probably already known, but mention it anyway. Package for Ubuntu 22.10 still needs to be added to repository.

**Comment by Prince781** [comment]
Not currently available in OBS, probably because it's recent.

I think people should also request the package be added to Ubuntu's official repos.

**Comment by EsoCoding** [comment]
I installed the 22.04, but i doubt if its working. Is there a way to test from terminal? In vscode i get something linted, but it just random words found in the script. Even comment data....

**Comment by Prince781** [comment]
I added 22.10 to OBS. Now, there is a separate problem with the key being out-of-date.

**Comment by EsoCoding** [comment]
I can't fully remember anymore how i did fix it, but i eventually solved it and had it working. Think i did use a wrong version from the ubuntu repository´s. Which nowadays has lots of outdated software. Reason why it crashed in vscode, have slipped my mind.
