### ISSUE TITLE
Autocompletion don't work wit VLS + Gnome Builder

### ISSUE THREAD

**Issue by bitseater** [vala-lang/vala-language-server#277]
**Describe the bug**
I can see tag description when mouse over a tag, but autocompletion don't work while typing

**Software**
OS and version (e.g. Ubuntu 20.04): Debian unstable + Gnome 43.1
Code editor (e.g. VSCode): Gnome Builder 43.4
Vala Language Server (e.g. git commit, or PPA/AUR version): git commit
Vala version (`valac --version`): 0.56.3

**To Reproduce**
1. Launch Gnome-Builder from terminal
2. Select any Project
3. Message in terminal : `TypeError: VlsSearchProvider.do_load() missing 1 required positional argument: 'context'`
4. Autocompletion don't work.

_N.D. :  I apologize about my bad english._

**Comment by benwaffle** [comment]
Can you try with the latest release?

And can you check in /usr/share/gnome-builder/plugins, /usr/local/share/gnome-builder/plugins, and ~/.local/share/gnome-builder/plugins for any VLS code? If you see any, you should delete it, as gnome-builder supports VLS out of the box now.

**Comment by bitseater** [comment]
**Software**
OS and version : Debian unstable + Gnome 43.3
Code editor : Gnome Builder 43.6
Vala Language Server :  0.48.7 (build from source)
Vala version (valac --version): 0.56.3

Working flawless. Thanks
