### ISSUE TITLE
Tag of 0.48.5 cannot pass

### ISSUE THREAD

**Issue by Decodetalkers** [vala-lang/vala-language-server#280]
**Describe the bug**
the old tag 0.48.5 cannot be compiled

**Software**
OS and version (e.g. Archlinux):
Code editor (e.g. VSCode):
Vala Language Server (e.g. git commit, or PPA/AUR version):
Vala version (`0.56.3):

**To Reproduce**
Source code repo:

1. download the tag 0.48
2. meson setup build
3. meson compile -C build

![image](https://user-images.githubusercontent.com/60290287/212331628-c75f8d88-6af4-4c04-b36d-3235446fe922.png)

I think something is wrong with the tag, master branch is ok

**Comment by Decodetalkers** [comment]
@Prince781 Can you make a new tag? I think this tag is break...

**Comment by benwaffle** [comment]
@Decodetalkers  please try version 0.48.7 in the AUR
