### ISSUE TITLE
vls-CRITICAL ** GLib-CRITICAL **

### ISSUE THREAD

**Issue by MachineTrader** [vala-lang/vala-language-server#288]
VSCode Output:
(vala-language-server:2529): vls-CRITICAL **: 02:23:28.721: string_slice: assertion '_tmp3_' failed
(vala-language-server:2529): GLib-CRITICAL **: 02:23:28.721: g_regex_match_full: assertion 'string != NULL' failed

These three statements, individually,  in Genie (Json) will cause above error message to, continuously flow, in the output tab of the vala language server in vscode. The code compiles nicely and works.

```
	if root.is_null ()
		print "Node is null"
	 	
	if root.get_node_type () == NodeType.ARRAY
		print "Node is array"
		
	if root.get_node_type () == NodeType.OBJECT
		print "Node is object"
```	

"is"  instead of "==" produces the same result.
The server was installed with: 
yay -S vala-language-server-git

```
Vala Language Server: 0.48.7-4-gc35dc69e
VSCodium Version: 1.76.2
OS: Linux x64 6.2.8-arch1-1
```

**Comment by Prince781** [comment]
Hi. Do you have a full example I can use to repro?

**Comment by MachineTrader** [comment]
Here's a full example. It retrieves a json array of crypto currencies and their price from Binance.
```
[indent=0] 

// Import the Soup module
uses 
	Soup
	Json

init	
	burl: string = "https://api4.binance.com/api/v3/" 
	json_string: string = http_get_request (burl,"ticker/price")	
	perform_parse (json_string)


def http_get_request(base_url:string ,url: string): string
	
	// Define the URL you want to make a request to	
	full_url:string = base_url + url	

	// Create a new Soup.Session object
	var session = new Soup.Session()

	// Create a new Soup.Message object and set its method and URL
	var message = new Soup.Message("GET",full_url)

	message.request_headers.append("Content-Type", "application/json")

	// Send the message and wait for the response
	session.send_message(message) 
	
	if message.status_code != 200
		stdout.printf ("Error: HTTP status code %d\n", (int)message.status_code)
		return ""
	
	var data = message.response_body.flatten().data

	data_str: string = (string)data

	// Print raw json
	print data_str

	return data_str


def perform_parse(message_body:string)	
	
	var parser = new Json.Parser()

	try
		parser.load_from_data((string)message_body, -1)
	except ex: Error
		stderr.printf("%s\n", ex.message)

	root: Json.Node = parser.get_root()	 
	if root.is_null () 
		print "Node is null"
		return
	
	if root.get_node_type () == NodeType.ARRAY
		arr: Json.Array = root.get_array()
	
		// Loop nodes in array
		for var e in arr.get_elements ()		
			var element = e.get_object ()			
			var symbol = element.get_string_member ("symbol")
			price_str:string = element.get_string_member ("price")		
			price_dbl:double = double.parse (price_str)
			print "%s %f ", symbol,price_dbl
		
	if root.get_node_type () == NodeType.OBJECT
		js_obj: Json.Object = root.get_object ()
	
		// Loop nodes in array
		for var e in js_obj.get_members ()		
			element:string = (string)e.data
		
			print "%s", element
```

**Comment by Prince781** [comment]
@MachineTrader please verify the branch `288-vls-critical-glib-critical` fixes your issue.

**Comment by MachineTrader** [comment]
Hi sorry for not getting back. I have problems building both the branch and the main. Not sure if there's something missing in my environment. It exits with this error after "Compilation succeeded - 75 warning(s)":
```
[157/243] Linking target subprojects/libgee/benchmark/benchmarks
ninja: build stopped: subcommand failed.
```

**Comment by MachineTrader** [comment]
Not sure what's going on, but installing with "yay -S vala-language-server-git" doesn't work any more and neither does "yay -S vala-langusge-server", I hope haven't broken my system.

The meson part works fine, but the ninja part fails:

Found ninja-1.11.1 at /usr/bin/ninja
ninja: Entering directory `build'
[1/49] Compiling Vala source ../test/testclient.vala ../src/util.vala
FAILED: test/vls-testclient.p/testclient.c test/vls-testclient.p/util.c 

Looks like a unit test fails.
I'll see if I can figure out what the first [1/49] test does.

**Comment by Prince781** [comment]
> `-X -I/usr/include/gtk-3.0 `

That's strange. VLS doesn't depend on GTK at all. You should not be seeing any references to that. Maybe run `git clean -fxd` or reclone the repo?

I've tested your issue and was able to fix it in the aforementioned branch.

**Comment by MachineTrader** [comment]
Yes the branch seem to work. I've reinstalled my computer now to get the compiling to work though. Why I had to do that I don't know.
