### ISSUE TITLE
No documentation about --pkg

### ISSUE THREAD

**Issue by cacilhas** [vala-lang/vala-language-server#298]
There’s no documentation about how to enable `--pkg`.

For instance, I have a project in VSCode that uses `--pkg  gtk+-3.0`, but `vala-language-server` keeps showing errors about the namespace Gtk could not be found, and the document explaining how to make it work is None.

**Comment by benwaffle** [comment]
You can either create a meson project, or add a `#/usr/bin/env -S vala --pkg gtk+-3.0` line at the top

**Comment by Hermholtz** [comment]
@benwaffle That would be so helpful if this line was in the main README.md. There's only a vague explanation there which is not clear at all for newbies.

**Comment by benwaffle** [comment]
Added here - https://github.com/vala-lang/vala-language-server/blob/master/README.md#specifying-dependencies

Let me know if there's a better place to put it.

**Comment by Hermholtz** [comment]
Thank you, that's helpful.
