### ISSUE TITLE
Organize all projects under a new group?

### ISSUE THREAD

**Issue by Prince781** [vala-lang/vala-language-server#78]
Perhaps we could organize all of these projects under a group like `vala-tools`? That might make it easier to keep track of things.

- benwaffle/vala-language-server
- prince781/vala-vscode
- benwaffle/vls-aur
- benwaffle/vls-aur-git
- prince781/vls-ubuntu
- prince781/vls-fedora

**Comment by benwaffle** [comment]
I've this project becomes production-ready I'd like it to go into https://github.com/vala-lang/
